version: '3'
services:
  gravcms:
    image: nmonst4/gravcms-docker
    ports:
    - "${PORT}:80"
    volumes:
    - ./user:/var/www/html/user
    environment:
      GRAV_VERSION: ${GRAV_VERSION}
volumes:
  data: